// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'feature/notes/data/dto/note_dto.dart';
import 'feature/notes/data/dto/todo_dto.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 5553712570427174702),
      name: 'NoteDto',
      lastPropertyId: const IdUid(5, 2805585802523121289),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6065927985713450609),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 116182608652044627),
            name: 'title',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 5628204122418295755),
            name: 'description',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 1574870769672364000),
            name: 'colorValue',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 2805585802523121289),
            name: 'dateTime',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[
        ModelRelation(
            id: const IdUid(1, 777071593035702795),
            name: 'todoList',
            targetId: const IdUid(2, 7518756833676447369))
      ],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 7518756833676447369),
      name: 'TodoDto',
      lastPropertyId: const IdUid(3, 6932048185317386447),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4234494403132190245),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 6606208358211091997),
            name: 'title',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 6932048185317386447),
            name: 'completed',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 7518756833676447369),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(1, 777071593035702795),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    NoteDto: EntityDefinition<NoteDto>(
        model: _entities[0],
        toOneRelations: (NoteDto object) => [],
        toManyRelations: (NoteDto object) =>
            {RelInfo<NoteDto>.toMany(1, object.id): object.todoList},
        getId: (NoteDto object) => object.id,
        setId: (NoteDto object, int id) {
          object.id = id;
        },
        objectToFB: (NoteDto object, fb.Builder fbb) {
          final titleOffset =
              object.title == null ? null : fbb.writeString(object.title!);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          final dateTimeOffset = object.dateTime == null
              ? null
              : fbb.writeString(object.dateTime!);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, descriptionOffset);
          fbb.addInt64(3, object.colorValue);
          fbb.addOffset(4, dateTimeOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = NoteDto(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              title: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              colorValue: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 10),
              dateTime: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              description: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8));
          InternalToManyAccess.setRelInfo<NoteDto>(
              object.todoList, store, RelInfo<NoteDto>.toMany(1, object.id));
          return object;
        }),
    TodoDto: EntityDefinition<TodoDto>(
        model: _entities[1],
        toOneRelations: (TodoDto object) => [],
        toManyRelations: (TodoDto object) => {},
        getId: (TodoDto object) => object.id,
        setId: (TodoDto object, int id) {
          object.id = id;
        },
        objectToFB: (TodoDto object, fb.Builder fbb) {
          final titleOffset =
              object.title == null ? null : fbb.writeString(object.title!);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addBool(2, object.completed);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = TodoDto(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              title: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              completed: const fb.BoolReader()
                  .vTableGetNullable(buffer, rootOffset, 8));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [NoteDto] entity fields to define ObjectBox queries.
class NoteDto_ {
  /// see [NoteDto.id]
  static final id = QueryIntegerProperty<NoteDto>(_entities[0].properties[0]);

  /// see [NoteDto.title]
  static final title = QueryStringProperty<NoteDto>(_entities[0].properties[1]);

  /// see [NoteDto.description]
  static final description =
      QueryStringProperty<NoteDto>(_entities[0].properties[2]);

  /// see [NoteDto.colorValue]
  static final colorValue =
      QueryIntegerProperty<NoteDto>(_entities[0].properties[3]);

  /// see [NoteDto.dateTime]
  static final dateTime =
      QueryStringProperty<NoteDto>(_entities[0].properties[4]);

  /// see [NoteDto.todoList]
  static final todoList =
      QueryRelationToMany<NoteDto, TodoDto>(_entities[0].relations[0]);
}

/// [TodoDto] entity fields to define ObjectBox queries.
class TodoDto_ {
  /// see [TodoDto.id]
  static final id = QueryIntegerProperty<TodoDto>(_entities[1].properties[0]);

  /// see [TodoDto.title]
  static final title = QueryStringProperty<TodoDto>(_entities[1].properties[1]);

  /// see [TodoDto.completed]
  static final completed =
      QueryBooleanProperty<TodoDto>(_entities[1].properties[2]);
}
